### ISSUE TITLE
Observation & Offer To Help

### ISSUE THREAD

**Issue by atki4564** [ShangtongZhang/reinforcement-learning-an-introduction#10]
Observation: If, line 46, self.qTrue.append(np.random.randn() + trueReward); where trueReward = 0
then why line 74, reward = np.random.randn() + self.qTrue[action] instead of
reward = self.qTrue[action]

Offer To Help: I'm new to python data analysis but not to financial programs (which is what, from my perspective, RL is, overall); so, if you want to assign me coding and/or analysis tasks in response to your 'help wanted' request, please ask. All I need is a requirements statement to help. Why? Because, this may sound a bit weird, but I think the survival of the human species depends upon the development of RL over the next 4 years; else it might be too late to help.

**Comment by ShangtongZhang** [comment]
You can refer to figure 2.1 to see how the true rewards and observed rewards is generated.
Thanks for your offer. Currently the only 'help wanted' issue is about the release date. If there is other issues about coding/analysis, I'd like to ask you for help. Thanks.
