### ISSUE TITLE
Chapter 09: Random Walk 100

### ISSUE THREAD

**Issue by xenomeno** [ShangtongZhang/reinforcement-learning-an-introduction#101]
Hello,

I am trying to reproduce the graph on figure 9.2(right) but on Lua. I read through you code and I noticed that with temporal difference n-step methods you use 100 actions on left/right. However in the book they say to match the example from Figure 7.2 they reduced the groups of state aggregation to 20 and also the actions on left/right from 100 to 50:

> In particular, recall that state transitions were
up to 100 states to the left or right. A typical transition would then be of 50 states to
the right or left, which is quantitatively analogous to the single-state state transitions of
the 19-state tabular system.

In your code you use STEP_RANGE = 100 both for DP, Monte Carlo and TD(n). Am I missing something here?

Thank you

P.S. Great repository by the way! Really helps!

**Comment by ShangtongZhang** [comment]
When I wrote the code the book is not complete, there may be some changes after I completed the code, which may result in inconsistency.
