### ISSUE TITLE
Maybe a little bug in chapter5 blackjack.py function 'play' line 81-85

### ISSUE THREAD

**Issue by Huixxi** [ShangtongZhang/reinforcement-learning-an-introduction#103]
```
while player_sum < 12:
    # if sum of player is less than 12, always hit
    card = get_card()
    player_sum += card_value(card)
    usable_ace_player = (card == 1)
```
what if the first card is `ace`, then the `player_sum += 11` and `usable_ace_player = True`, now next loop, the second card is one of `2--10`, so the variable `usable_ace_player` is changed from  `True` to `False`, but the player indeed use an `ace` as `11`, which means `usable_ace_player ` should be `True`, I don't know whether it is a right illustration. So I suggest:
```
cards = [] 
while player_sum < 12:
    card = get_card()
    cards.append(card)
    player_sum += card_value(card)
usable_ace_player = (1 in cards)
```
like what you did to the dealer's `usable_ace_dealer`

**Comment by ShangtongZhang** [comment]
Thanks for pointing this out! 
I think you are right. I have included your fix.
