### ISSUE TITLE
Chapter 4：seems missing self. before TRUNCATE

### ISSUE THREAD

**Issue by ChaiZQ** [ShangtongZhang/reinforcement-learning-an-introduction#113]
for req1 in range(0, self.TRUNCATE):
    for req2 in range(0, self.TRUNCATE):

in this kind of situations, seems missing "self." before "TRUNCATE", so it will cause errors like TRUNCATE not defined.

**Comment by ShangtongZhang** [comment]
Fixed. Thanks!
