### ISSUE TITLE
How to formulate problem with State is a combination of multiple factors?

### ISSUE THREAD

**Issue by MJeremy2017** [ShangtongZhang/reinforcement-learning-an-introduction#114]
Hi, shangtong
I am reading the book and following your implementation code.
In chapter 9, the `random walk` example, the book mentioned `V(s, w) = W*S`, where in `random walk` the state is 1 dimension, in its simplest form it could be like `V(s, w) = w_1*s + w_0`, but I wonder what if the state has 2 or more components? 
say, `S = S(position, time)`, how to rewrite the above function? Is it `V(s, w) = w_1*(position + time) + w_0`?

**Comment by ShangtongZhang** [comment]
function approximation with features, e.g., tile coding
