### ISSUE TITLE
Reinforcement learning 

### ISSUE THREAD

**Issue by palbha** [ShangtongZhang/reinforcement-learning-an-introduction#120]
Hi Shangtong , I am new to the reinforcement learning part , I have a sceanrio in which I have a machine learning model predicting target properly.I want to figure out the input paramters so as to attain a particular target value .Any suggestions will be great ..
The input parameter may range from 4-20 and since the input parameters are discrete numeric values there may be lot many combinations of the same .

**Comment by ShangtongZhang** [comment]
Sorry I have no idea about this.
