### ISSUE TITLE
chapter04/car_rental_synchronous.py: the table needs to be flipped.

### ISSUE THREAD

**Issue by QuangTran4810** [ShangtongZhang/reinforcement-learning-an-introduction#124]
I think the table plot of the policy need a small correction. It needs to be flipped before plotted:
plt.table(cellText=np.flipud(self.policy), loc=(0, 0), cellLoc='center')
Otherwise the y-label and the policy will mismatch.

**Comment by ShangtongZhang** [comment]
Fixed, thanks for pointing this out!
