### ISSUE TITLE
chap1/tic_tac_toc.py why does make td_error zero when exploring

### ISSUE THREAD

**Issue by GarfieldF** [ShangtongZhang/reinforcement-learning-an-introduction#125]
td_error = self.greedy[i] * (
                self.estimations[states[i + 1]] - self.estimations[state]
            )

#when exloring greedy is false
 if np.random.rand() < self.epsilon:
            action = next_positions[np.random.randint(len(next_positions))]
            action.append(self.symbol)
            self.greedy[-1] = False
This operation would make exploration meaningless, wouldn't it?

**Comment by ShangtongZhang** [comment]
No. Because the td errors for the transitions after the exploration step is not zero.
