### ISSUE TITLE
Chapter4, gambler problem

### ISSUE THREAD

**Issue by 07hyx06** [ShangtongZhang/reinforcement-learning-an-introduction#127]
is this another optimal policy?

![figure_4_3_2](https://user-images.githubusercontent.com/52267384/79461117-50bf8f80-8028-11ea-9066-0ba934ceb890.jpg)

The textbook mentioned that there are various optimal policy...

**Comment by ShangtongZhang** [comment]
Yeah I remember this is also optimal.
