### ISSUE TITLE
Help on ten_armed_testbed.py

### ISSUE THREAD

**Issue by huang-ying** [ShangtongZhang/reinforcement-learning-an-introduction#128]
Why there are still `np.random.choice` in Line 66/74? It should be a definite number from argmax. Thanks.

**Comment by ShangtongZhang** [comment]
There could be a tie.

**Comment by huang-ying** [comment]
As shown below, Line 74 always choose the first element by `[0]` when there is a tie. The input to `np.random.choice` is an int instead of an array.
```python
np.random.choice(np.where(self.q_estimation == q_best)[0])
```

**Comment by ShangtongZhang** [comment]
You can set a breakpoint and run the code to see what happens.
