### ISSUE TITLE
Generalization to abstract classes for Environment/Agents?

### ISSUE THREAD

**Issue by chicotobi** [ShangtongZhang/reinforcement-learning-an-introduction#141]
Hey, I just did the Coursera-Courses from Adam and Martha White. The code examples there made use of an abstract generic environment/agent framework. I have been thinking of replicating the figures (and exercises) from the book using such framework.

The advantage would be not only to accompany the examples from the book, but easily comparing algorithms across the chapters on several examples.

I know that there are other packages, e.g. gym, that already provide such abstraction, but I think there could still be some benefit for other students, especially because your package is referenced on Sutton's homepage.

What do you think? I guess you maybe already considered this?

**Comment by ShangtongZhang** [comment]
The principle when I wrote this repo is to make the script as simple as possible, e.g., each .py file should be self-contained.

**Comment by chicotobi** [comment]
Hey thanks for the answer, yeah, I can see where you come from, I am doing it now on my own.
