### ISSUE TITLE
Maybe Error in Chapter03/GridWorld.py

### ISSUE THREAD

**Issue by ZiJianZhao** [ShangtongZhang/reinforcement-learning-an-introduction#26]
In the GridWorld.py, you write the code using bellman equation to update the value function:
```Python
while True:
    # keep iteration until convergence
    newWorld = np.zeros((WORLD_SIZE, WORLD_SIZE))
    for i in range(0, WORLD_SIZE):
        for j in range(0, WORLD_SIZE):
            for action in actions:
                newPosition = nextState[i][j][action]
                # bellman equation
                newWorld[i, j] += actionProb[i][j][action] * (actionReward[i][j][action] + discount * world[newPosition[0], newPosition[1]])
    if np.sum(np.abs(world - newWorld)) < 1e-4:
        print('Random Policy')
        print(newWorld)
        break
    world = newWorld
```
In the last line, 
```Python
    world = newWorld
```
This assignment will cause the *world* and *newWorld* to share the same address and content. This is also right because it can be seen as the asynchronous updating. But if you want to implement the asynchronous way, I think there is no need to use two variables. So, I believe that this is a error, and the right implementation should be:
```Python
    world = copy.deepcopy(newWorld)
``` 
Thank for you  reply in advance.

**Comment by zhuoyu** [comment]
Thank you for sharing this.

Zhuoyu

2017年2月20日 上午6:22，Zhao Zijian <notifications@github.com>写道：

In the GridWorld.py, you write the code using bellman equation to update the value function:

while True:
    # keep iteration until convergence
    newWorld = np.zeros((WORLD_SIZE, WORLD_SIZE))
    for i in range(0, WORLD_SIZE):
        for j in range(0, WORLD_SIZE):
            for action in actions:
                newPosition = nextState[i][j][action]
                # bellman equation
                newWorld[i, j] += actionProb[i][j][action] * (actionReward[i][j][action] + discount * world[newPosition[0], newPosition[1]])
    if np.sum(np.abs(world - newWorld)) < 1e-4:
        print('Random Policy')
        print(newWorld)
        break
    world = newWorld

In the last line,

    world = newWorld

This assignment will cause the world and newWorld to share the same address and content. This is also right because it can be seen as the asynchronous updating. But if you want to implement the asynchronous way, I think there is no need to use two variables. So, I believe that this is a error, and the right implementation should be:

    world = copy.deepcopy(newWorld)

Thank for you reply in advance.

**Comment by ShangtongZhang** [comment]
Thanks, I intended to do asynchronous updating. Although the naming is somehow confusing...
Actually there was a commit to check all the things with deep copy. Anyway thanks for your sharing and I'll fix the naming.

**Comment by ShangtongZhang** [comment]
No. At the beginning of every loop,
`newWorld = np.zeros((WORLD_SIZE, WORLD_SIZE))`
`newWorld` will be assigned to a new zero matrix, while `world` is still the old one.

**Comment by ShangtongZhang** [comment]
If it's in-place update, `if` statement will always be true.

**Comment by ZiJianZhao** [comment]
Ok, you are right. I'm sorry for this stupid issue.
