### ISSUE TITLE
debug errors for missing modules

### ISSUE THREAD

**Issue by Heaven91** [ShangtongZhang/reinforcement-learning-an-introduction#27]
Hi, 

I forked you repository and clone to my local workspace, then installed the whole package with `python  setup.py install`. The package is successfully installed and I can see the package name with `pip list`. The problem is I can run every script files and functions successfully in a terminal with command `python **name**.py`, but I cannot run the module alone, which means I open the specific file and run the file in a IDE like spyder or use **Ctrl+b** in sublime. I thought it is related to the python packing functions. Could you give me some explanations?

Thanks

**Comment by ShangtongZhang** [comment]
Hi,
There is no need to run `python setup.py install`. That file is for Travis.CI. If you want to run it in terminal, just follow the usage section in readme. I use PyCharm, it works well for me. Just put the bunch of folders into your IDE. And make sure the root dir of this project is in `PYTHONPATH`

**Comment by ShangtongZhang** [comment]
Hi, 
there is no need to run
