### ISSUE TITLE
Policy Iteration in Chapter4 for RentalCar 

### ISSUE THREAD

**Issue by loopinvariant4** [ShangtongZhang/reinforcement-learning-an-introduction#28]
Hi,

In the RentalCar.py code, I noticed an issue where the policy evaluation is only being iterated to convergence the first time. For subsequent times, policy evaluation is iterated just once and then it tries to improve the policy.

To fix this, you need to set the boolean PolicyImprovement to false after each time the PolicyImprovement block of code is run.

This results in a change to the final values of the state and the convergence occurs in fewer steps.

Let me know if you agree with my findings and i can submit a pull request for the fix.

Thank you for sharing this code. I find this very helpful in my study of the 2nd edition book.

**Comment by ShangtongZhang** [comment]
Yeah it's indeed a bug. Could you submit a PR to fix this? And don't forget to add your copyright information in the header of that file. Thanks!

**Comment by loopinvariant4** [comment]
Thank you for getting back to me so soon. I'll submit the PR now. Could you please explain what you mean by copyright information in the header? I am not affiliated with any organization. What information would you like me to add in there?

Thank you

**Comment by ShangtongZhang** [comment]
Your name and email, like this
#######################################################################
# Copyright (C)                                                       
# 2016 Shangtong Zhang(zhangshangtong.cpp@gmail.com)                  
# 2016 Kenta Shimada(hyperkentakun@gmail.com)                         
# Permission given to modify the code as long as you keep this        
# declaration at the top                                              
#######################################################################
But of course, it depends on you whether to add it or not.
Thanks~

**Comment by ShangtongZhang** [comment]
Thanks for your contribution!
