### ISSUE TITLE
Ch02 TenArmedTestbed sampleAverage

### ISSUE THREAD

**Issue by wugh** [ShangtongZhang/reinforcement-learning-an-introduction#34]
Hi, Zhang

I have some confuse about the sample average equation use in code
```python
self.qEst[action] += 1.0 / self.actionCount[action] * (reward - self.qEst[action])
```
In the book, the equation is:
```
self.qEst[action] = sum(the reward get when execute specific action in past time) / self.actionCount[action] 
```
I dont think this two equation is equivalence.

**Comment by ShangtongZhang** [comment]
They are indeed the same.
See[ incremental averaging](http://math.stackexchange.com/questions/106700/incremental-averageing)

**Comment by wugh** [comment]
Thank You~~
