### ISSUE TITLE
should there be some changes about the code in chapter 12 "Eligibility Traces", RandomWalk.py, class "OffLineLambdaReturn" function "nStepReturnFromTime"

### ISSUE THREAD

**Issue by xiaogengyaokeyan** [ShangtongZhang/reinforcement-learning-an-introduction#35]
the code from the author zhang is:
` # get the n-step return from the given time
    def nStepReturnFromTime(self, n, time):
        # gamma is always 1 and rewards are zero except for the last reward
        # the formula can be simplified
        endTime = min(time + n, self.T)
        returns = self.value(self.trajectory[endTime])
        if endTime == self.T:
            returns += self.reward
        return returns
`
which I think should be like this:
` # get the n-step return from the given time
    def nStepReturnFromTime(self, n, time):
        # gamma is always 1 and rewards are zero except for the last reward
        # the formula can be simplified
        endTime = min(time + n, self.T)
        #test
        if endTime == self.T:
            returns = self.reward
        else:
            returns = self.value(self.trajectory[endTime])
        return returns
        #test`
this is confused, can somebody help me out?

**Comment by ShangtongZhang** [comment]
As far as I can see, if take the fact that ```self.value(final_state)``` is 0 into consideration, both implementations are same.

**Comment by xiaogengyaokeyan** [comment]
would `self.value(final_state)` stay unchanged during learning?

**Comment by ShangtongZhang** [comment]
It should stay unchanged. If it gets changed somehow, then it's a bug.

**Comment by xiaogengyaokeyan** [comment]
in this example, state aggregation is used to approximate the value function, in my opinion, the wights would get changed during learning, so do `self.value(final_state)`. Is this right?

**Comment by ShangtongZhang** [comment]
No. What if learning never happens for the final state? Then it will always stay the initial value 0.

**Comment by xiaogengyaokeyan** [comment]
All right, thank you zhang!
