### ISSUE TITLE
Tic-Tac-Toe program didn't work well when AI is player 2.

### ISSUE THREAD

**Issue by shengchun** [ShangtongZhang/reinforcement-learning-an-introduction#36]
Hi Shangtong,

When I tested this tic-tac-toe AI program, I found that AI didn't play well as player 2. I think the tie rewards are not properly. If set tie rewards as 0.1/0.5 for player1/player2. Then this AI program works very well for both player 1&2. Below is modified code.
```python
    # give reward to two players
    def giveReward(self):
        if self.currentState.winner == self.p1Symbol:
            self.p1.feedReward(1)
            self.p2.feedReward(0)
        elif self.currentState.winner == self.p2Symbol:
            self.p1.feedReward(0)
            self.p2.feedReward(1)
        else:
            self.p1.feedReward(0.1)
            self.p2.feedReward(0.5)
```

**Comment by ShangtongZhang** [comment]
Thanks! It looks reasonable. If P1 adopts optimal policy, P2 can never win. So we should give P2 more reward for tie than P1. Would you like to open a PR about this?

**Comment by ShangtongZhang** [comment]
I just updated the code. Thanks a lot for pointing this out!
