### ISSUE TITLE
ImportError: No module named utils.utils

### ISSUE THREAD

**Issue by SJTUGuofei** [ShangtongZhang/reinforcement-learning-an-introduction#37]
When i'm running some examples, there comes out "ImportError: No module named utils.utils" , I see there exists subdirectory named "utils' and "extra" under the main directory, but I don't known how to load these two self-defined packages into the programs?

**Comment by ShangtongZhang** [comment]
Please follow the usage section in readme strictly (including in which directory to run the script). Otherwise you have to make sure path of utils directory is in current python path by yourself.

**Comment by vadimq** [comment]
The instructions work on Linux, but produce a similar error on Windows.

**Comment by ShangtongZhang** [comment]
Hi @vadimq , I'm so sorry that I cannot provide support for Windows as I only have mac and ubuntu. I believe all is about to configure path properly.

**Comment by vadimq** [comment]
@ShangtongZhang Thank you for the fast response. I ended up installing the repository as a package using `pip install -e reinforcement-learning-an-introduction/` after cloning.

**Comment by ShangtongZhang** [comment]
@vadimq That's awesome! Maybe I should add `sys.path.append` later on to solve this problem thoroughly.

**Comment by Tipplynne** [comment]
Hmm... I am also having trouble. I changed the script TenArmedTestbed.py to include; import sys
sys.path.append('../utils')
from utils import *
But now am getting a name Error (name 'argmax' is not defined)
Using Mac and vamdimq's approach does not work either.

**Comment by ShangtongZhang** [comment]
@Tipplynne It seems time for me to totally solve this problem -- I just totally removed the `utils` folder. Please update to the latest version and it should work well.
