### ISSUE TITLE
exercise 4.8

### ISSUE THREAD

**Issue by persistforever** [ShangtongZhang/reinforcement-learning-an-introduction#40]
![image](https://cloud.githubusercontent.com/assets/9996015/25908405/b20f3a2c-35dc-11e7-8efd-3e06ccf29d34.png)
this is your picture 

![image](https://cloud.githubusercontent.com/assets/9996015/25908441/cc600834-35dc-11e7-9fe2-be3eed8ee9db.png)
this is my picture

![image](https://cloud.githubusercontent.com/assets/9996015/25908508/f55f41a0-35dc-11e7-9fa2-1a850ab83a5c.png)
but we both don't get the picture in the book like this

**Comment by ShangtongZhang** [comment]
I think this https://github.com/ShangtongZhang/reinforcement-learning-an-introduction/issues/39 may help.

**Comment by persistforever** [comment]
@ShangtongZhang thank you!
