### ISSUE TITLE
chapter4:Gambler question. Cannot reproduce result, why?

### ISSUE THREAD

**Issue by lvlvlvlvlv** [ShangtongZhang/reinforcement-learning-an-introduction#41]
hi there. i am also trying to write some code for exercises in this book.
But i get stuck at chapter4--the Gambler question.
I refer to your code and compare the result with mine. we both get the similar result.But the result is far away from the result in book.
I want to know the reasons or some of your opinion about this question.
Thank you!

**Comment by ShangtongZhang** [comment]
I think this https://github.com/ShangtongZhang/reinforcement-learning-an-introduction/issues/39 may help.

**Comment by lvlvlvlvlv** [comment]
@ShangtongZhang   Thank you very much. That #39 helps a lot!
