### ISSUE TITLE
A little problem in the Gambler‘s question in chapter4

### ISSUE THREAD

**Issue by lvlvlvlvlv** [ShangtongZhang/reinforcement-learning-an-introduction#42]
hi there，I have some confusion with your code about “The Gambler question ” in chapter 4.
here is part of code:

`
# value iteration

while True:

    delta = 0.0

    for state in states[1:GOAL]:

        # get possilbe actions for current state

        actions = np.arange(min(state, GOAL - state) + 1)

        actionReturns = []

        for action in actions:

            actionReturns.append(headProb * stateValue[state + action] + (1 - headProb) * stateValue[state - action])

        newValue = np.max(actionReturns)

        delta += np.abs(stateValue[state] - newValue)

        # update state value

        stateValue[state] = newValue

    if delta < 1e-9:

        break
`

I wonder why you didn't add the win-reward as 1 when head of coin appear in the following line:

`
actionReturns.append(headProb * stateValue[state + action] + (1 - headProb) * stateValue[state - action])
`

ps: I add the win-reward as 1 when head of coin appears but thus get the value over 2, not limited by 1 as probability. So it confused me because the value iteration update rule is saying:

![image](https://user-images.githubusercontent.com/18740554/27166636-c38992f8-51ce-11e7-9a29-16a4a5b88017.png)

Look forward to your reply! 
Thank you!

**Comment by ShangtongZhang** [comment]
see line 26

**Comment by lvlvlvlvlv** [comment]
@ShangtongZhang 
Thank you for your attention.
However, when set state[goal]=1,why don't need add the reward part as 1 when achieve the goal.

![](https://user-images.githubusercontent.com/18740554/27166636-c38992f8-51ce-11e7-9a29-16a4a5b88017.png)

where is the "r(s,a,s')" part? shouldn't it also be set to 1 when state[goal] =1.
Still not very clear about that. Am I understand something wrong?

**Comment by ShangtongZhang** [comment]
`1 + gamma * 0` is equal to `0 + gamma * 1` if `gamma == 1`

**Comment by lvlvlvlvlv** [comment]
@ShangtongZhang 
Thank you for your answer.
but `1 + gamma * 1` won't happen? `r(s,a,s')=1,gamma=1,and v(state=goal)=1`?
why is it that when you say r(s,a,s')=1, you defaultly set v(state=goal)=0 or when you say v(state=goal) == 0 , you defaultly set r(s,a,s')=0?
why these two part `r(s,a,s')=1` and ` v(state=goal)=1` cannot exist at the same time when the goal is achieved?
Hopefully i make myself more clear.

**Comment by ShangtongZhang** [comment]
You may find exercise 4.8 helpful

**Comment by lvlvlvlvlv** [comment]
@ShangtongZhang 
Have thought about exercise 4.8. Honestly, can't figure it out.
Could you please send me a copy of solutions about exercises? 
:-)
Thank you!

**Comment by ShangtongZhang** [comment]
I guess the pdf solution doesn't exist. You should think harder by yourself.

**Comment by lvlvlvlvlv** [comment]
@ShangtongZhang 
OK. I think I've got it. Thank you for your patience and lucid code.
