### ISSUE TITLE
Example 4.3 Gambler's Problem Cannot Reproduce Book's Plotting

### ISSUE THREAD

**Issue by superxingzheng** [ShangtongZhang/reinforcement-learning-an-introduction#44]
https://github.com/superxingzheng/test/blob/master/reinforcement_learning/GamblersProblem/main.cpp

This is my implementation. Not only the tied best actions can cause different plotting. If we add the +1 reward gained from the transition to the Goal ( capital 100) state, the value of capital 99 state will approach 2.0 not 1.0.

**Comment by ShangtongZhang** [comment]
https://github.com/ShangtongZhang/reinforcement-learning-an-introduction/issues/42

**Comment by superxingzheng** [comment]
You are right. Thanks! After this fix, my code does the same as yours. With 20 value iterations, the best action plotting looks similar to the book's.

**Comment by superxingzheng** [comment]
![gamblersproblem](https://user-images.githubusercontent.com/3332414/27687544-3b634c16-5ca5-11e7-9e02-e1507d5cb495.png)
