### ISSUE TITLE
About the action selection in Double Q-Learning

### ISSUE THREAD

**Issue by ewanlee** [ShangtongZhang/reinforcement-learning-an-introduction#46]
If two action have the same state-action value, then use the **np.argmax()** method will always return the first action. So I change the implementation (MaximizationBias.py):
```
# choose an action based on epsilon greedy algorithm
def chooseAction(state, stateActionValues):
    if np.random.binomial(1, EPSILON) == 1:
        return np.random.choice(stateActions[state])
    elif state == STATE_A and len(set(stateActionValues[0])) == 1:
        return np.random.choice(stateActions[state])
    else:
        return np.argmax(stateActionValues[state])
```

**Comment by ShangtongZhang** [comment]
Thanks for the contribution! That's true. 
You may find this issue https://github.com/ShangtongZhang/reinforcement-learning-an-introduction/issues/37 interesting.
At the very beginning I also noticed this and implemented my own `argmax` and put it into a `utils` folder. Although I believe the usage is well documented, many people still complain about `import error` in the above issue. So about a month ago, I deleted my own `argmax` and use `np.argmax` all the time.

**Comment by ewanlee** [comment]
@ShangtongZhang Thanks for your reply :D  
By the way, I found the **Example 6.7 Maximization Bias Example** cannot reproduce book's plotting. Could I open a new issue?

**Comment by ShangtongZhang** [comment]
@ewanlee Sure. I'll look into that.

**Comment by ewanlee** [comment]
@ShangtongZhang WOW! I found the plotting is true when I fixed this issue. 
Thank you very much, anyway :P
