### ISSUE TITLE
questions on Q-learning applied for racetrack

### ISSUE THREAD

**Issue by lvlvlvlvlv** [ShangtongZhang/reinforcement-learning-an-introduction#47]
hi @aoboturov @kentan @ndvanforeest @vfdev-5 @datahaki : 

I have tried implement standard Q-learning and Sarsa algorithm on a simple racetrack map. And it's very strange that while Sarsa converge very quick but Q-learning is so hard to converge in nearly same iterations(5000~10000) under same environment. WHY???

The code for generating episodes is always the same and I limit each episode in 200 time steps.
I initialize two policy with tabular form. one is for generating episode, named 'mu',it's e-greedy; another is target policy,named 'pi',it's deterministic. In every step of one episode, I keep updating 'mu' every time after I updating current Q(s,a), and set the target policy 'pi' with greedy form.

Here is my Q-learning code:
`

ep_idx = 0 	avg_ep_return_list = [] 	while ep_idx < episode_num:              '''evaluation part: Every 'eval_interval' episodes, use target policy pi generate one episode to see the total return''' 		if ep_idx % eval_interval == 0: 			eval_ep = agent.episode_generator(self.pi,max_timestep,False) 			print("eval episode length:%d" %(len(eval_ep)/3)) 			c_avg_return = agent.avg_return_per_episode(eval_ep) 			avg_ep_return_list.append(c_avg_return) 			print("assessing return:%f" %c_avg_return) 			print "avg return list length:",len(avg_ep_return_list)  		ep_idx += 1  		agent.c_state = agent.getInitState() 		agent.next_state = agent.c_state  		n = 0 		while n < max_timestep:  			agent.c_state  = agent.next_state  			c_action_idx = np.random.choice(self.action_num,1,p=self.mu[agent.c_state])[0]  			agent.c_state, agent.c_action, agent.c_reward, agent.next_state = agent.oneStep_generator()   			if agent.isTerminated(): 				Qmax = 0 			else: 				Qmax = np.amax(self.Q[agent.next_state])  			self.Q[agent.c_state][c_action_idx] += alpha * ( 			agent.c_reward + gamma * Qmax - self.Q[agent.c_state][c_action_idx])  			c_best_action_idx = np.argmax(self.Q[agent.c_state]) 			                              # --------behavior policy update at each step---------# 			for action_idx in range(self.action_num): 				if action_idx == next_best_action_idx: 					self.mu[agent.c_state][action_idx] = 1 - epsilon + epsilon/self.action_num 				else: 					self.mu[agent.c_state][action_idx] = epsilon/self.action_num   			# --------target policy update at each step---------# 			for action_idx in range(self.action_num): 				if action_idx == c_best_action_idx: 					self.pi[agent.c_state][action_idx] = 1.0 				else: 					self.pi[agent.c_state][action_idx] = 0.0  			n += 1  	return avg_ep_return_list`
--

`

**Comment by ShangtongZhang** [comment]
In principle I only respond to bugs or improvements about my python implementations here. For general RL question or environment unrelated to the book, Quora or mathoverflow may be a better place. So I'm sorry I'll close this issue.
