### ISSUE TITLE
Sarsa, Q-Learning Optimal Policy Output is Not Optimal

### ISSUE THREAD

**Issue by mosicr** [ShangtongZhang/reinforcement-learning-an-introduction#48]
Hi, 
When I run CliffWalking.py from Chapter 6 I get this as optimal policy output ( graphs look great btw ):
Sarsa Optimal Policy:
['R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'D']
['U', 'U', 'U', 'U', 'U', 'R', 'U', 'U', 'U', 'U', 'R', 'D']
['R', 'U', 'L', 'R', 'L', 'U', 'R', 'U', 'U', 'L', 'R', 'D']
['U', 'U', 'U', 'U', 'U', 'U', 'U', 'U', 'U', 'U', 'U', 'G']
Q-Learning Optimal Policy:
['L', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'D']
['R', 'R', 'R', 'R', 'R', 'R', 'D', 'R', 'R', 'R', 'R', 'D']
['R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'D']
['U', 'U', 'U', 'U', 'U', 'U', 'U', 'U', 'U', 'U', 'U', 'G']

These are not optimal - if you follow them in cliff gridworld they lead to nowhere. 
Any comments ? 
Regards, Ranko.

**Comment by ShangtongZhang** [comment]
Why? Starting from the 3rd row in the 1st column, it's a R, then follow it you will just end up with G.

**Comment by mosicr** [comment]
Thank you Shangtong, my bad, I didn't realize output is laid out as cliff gridworld. 

Much appreciated !!

**Comment by mosicr** [comment]
Note: changing the number of runs from 10 to 30 makes it produce the output.
