### ISSUE TITLE
Could you please help to answer some questions?

### ISSUE THREAD

**Issue by JieMEI1994** [ShangtongZhang/reinforcement-learning-an-introduction#49]
I try to re-implement your code but have met some problem, so I wonder would you mind helping answer some questions?
Because I just started from chapter one, so the first question comes from the chessman algorithm. And here are parts of your code.

# check diagonals
        results.append(0)
        for i in range(0, BOARD_ROWS):
            results[-1] += self.data[i, i]
        results.append(0)
        for i in range(0, BOARD_ROWS):
            results[-1] += self.data[i, BOARD_ROWS - 1 - i]

Why you write this command "results.append(0)" and what is the different targets between those two "for function"?

**Comment by ShangtongZhang** [comment]
Sorry I'm fairly busy recently. In the foreseen future I'm afraid I don't have time to respond to issues except bugs.

**Comment by ShangtongZhang** [comment]
Sorry for the late response.
`results.append(0)` is to set up the initial value of the sum of the values in the diagonal.
The two `for` compute the sum of the values in the two diagonals.
