### ISSUE TITLE
Shouldn't update state action value using absolute priority in Priority Sweeping

### ISSUE THREAD

**Issue by wumo** [ShangtongZhang/reinforcement-learning-an-introduction#50]
Relevant code is :
https://github.com/ShangtongZhang/reinforcement-learning-an-introduction/blob/f5f43347dacfbbbe01780f0c2786da1a0b717ffe/chapter08/VariousMaze.py#L364

priority=abs(R+gamma*max_aQ(s'.a)-Q(s,a))
However stateActionValue should be updated using R+gamma*max_aQ(s'.a)-Q(s,a) which isn't equal to priority.

**Comment by ShangtongZhang** [comment]
Thanks a lot for pointing it out!
I have fixed it just now.
It also helps me find another bug about `np.argmax' https://github.com/ShangtongZhang/reinforcement-learning-an-introduction/issues/51
