### ISSUE TITLE
One question posted on SOF

### ISSUE THREAD

**Issue by cinqs** [ShangtongZhang/reinforcement-learning-an-introduction#56]
Hi, we are currently reading the book, and had a question posted on StackOverflow, could you please to give any hint, or thought.

This is the link:

https://datascience.stackexchange.com/questions/25362/cannot-see-what-the-notation-abuse-is-mentioned-by-author-of-book/25389#25389

**Comment by ShangtongZhang** [comment]
I don’t know the answer. The answer in the link looks reasonable to me.
