### ISSUE TITLE
Is there any boundary for policies with off-policy Q-learning using the tree backup algorithm?

### ISSUE THREAD

**Issue by marktimarev** [ShangtongZhang/reinforcement-learning-an-introduction#57]
Hi.

The question is related to TD learning using the n-step Tree Backup Algorithm and also to the later unification work: https://arxiv.org/abs/1703.01327

In the book, it has been mentioned a few times that the Tree Backup Algorithm by itself is natural extension of the Q-learning algorithm to a multi-step representation. However, considering about "off-policiness" I figured out the algorithm does not seem to be able to search the greedy optimum policy where only the optimal actions have some positive probability and all others are zeros. On the other hand, it is exactly what does the one-step Q-learning algorithm (that is also the reason the Q-learning is an off-policy method in contrast to the SARSA method).

However, it seems the chain of n-steps is being teared in places it comes out the optimal policy if the target policy is absolutely greedy. Therefore, using the more sophisticated, unifying algorithm such breaks should be filled out by going through the expected SARSA leafs but we cant because of all other actions have zero probability in absolutely greedy target policy case.

In the paper, we see some experiments with e-greedy target policies but cases with absolutely greedy were not mentioned as it was not mentioned is a target policy like in one-step Q-learning algorithm possible/reasonable.

I'm curious about your explicit thoughts about it. I found some mentions about lack of the tree backup algorithm to find efficiently for the reason that it tends to tear sequences, as you described in the summary after the chapter, but it was not discussed anywhere the algorithms are presented. So, could you, please, share your experience about some like cases?

Thanks in advance and many thanks for your work!

**Comment by ShangtongZhang** [comment]
Sorry I have no idea about this.
