### ISSUE TITLE
First-visit MC prediction for estimating v_pi

### ISSUE THREAD

**Issue by huanghua1668** [ShangtongZhang/reinforcement-learning-an-introduction#59]
Hi there, I have a question to the implementation of the MC on policy evaluation algorithm. First Visit MC algorithm at page 76, In the final draft version of the book, says that "...for each state s appear in the episode...", while in the code (https://github.com/ShangtongZhang/reinforcement-learning-an-introduction/blob/master/chapter05/Blackjack.py), at line 189, seems only the initial state of each episode is sampled, and all the other states in playerTrajectory are discarded. I think these states also appears the first time in the episode, so it might be beneficial to take them into account for sampling the state values. I tested this change by modifying line 189 to 
for _, (usableAce, playerSum, dealerCard) in playerTrajectory:
            state[0]=usableAce
            state[1]=playerSum
            state[2]=dealerCard
Now all the states will be sampled, and the results looks quite similar to the old results. 

You guys have any idea? I might be wrong, and if so, thank you for pointing them out.

**Comment by ShangtongZhang** [comment]
I think you are absolutely right. Would you mind making a PR? I can also do it myself.
