### ISSUE TITLE
Chapter 4, Gambler's problem incorrect output

### ISSUE THREAD

**Issue by B2VS** [ShangtongZhang/reinforcement-learning-an-introduction#62]
The policy is incorrect as it's not the same as the one given in the textbook. The correct output should be:
![image](https://user-images.githubusercontent.com/20512402/35576087-29e4b660-0604-11e8-98ad-c07188c0a70d.png)

**Comment by ShangtongZhang** [comment]
https://github.com/ShangtongZhang/reinforcement-learning-an-introduction/issues?utf8=%E2%9C%93&q=gambler

**Comment by B2VS** [comment]
Hm... it's true that there exists multiple points where the maximum occurs however one of those points should match with the given graph.... According to datahaki (on issue # 39) these points are matching, however the output doesn't output those points. The output run on my machine is:
![image](https://user-images.githubusercontent.com/20512402/35576812-efb3afe4-0605-11e8-8527-d38bf419883b.png)
For example, take capital = 95, the output is showing 0, however it should be 5
