### ISSUE TITLE
Policy evaluation for GridWorld

### ISSUE THREAD

**Issue by cbrom** [ShangtongZhang/reinforcement-learning-an-introduction#67]
The current method of prediction (policy evaluation) is iterative update of value function by an equi-probable actions.
But what if we update the values and action probabilities concurrently?
Or is what I am describing now the `policy iteration concept`?
Can I modify version of GridWorld in chapter04 and ask for a pull request?
@ShangtongZhang

**Comment by ShangtongZhang** [comment]
Figure 4.1 is only policy evaluation not policy iteration, so we should not change the random policy. And even you do policy iteration I do see the reason to use a softmax, unless you are working on soft q-learning. https://arxiv.org/abs/1704.06440

**Comment by cbrom** [comment]
So, by changing the action probabilities I am doing `policy iteration`?

**Comment by ShangtongZhang** [comment]
yes

**Comment by cbrom** [comment]
Hey I came to a realization that for it to be a policy iteration it must satisfy this one
`1. Initialization
V (s) ∈ R and π(s) ∈ A(s) arbitrarily for all s ∈ S
2. Policy Evaluation
Repeat
∆ ← 0
For each s ∈ S:
v ← V (s)
V (s) ← s ,r p(s , r |s, π(s)) r + γV (s )
∆ ← max(∆, |v − V (s)|)
until ∆ < θ (a small positive number)
3. Policy Improvement
policy-stable ← true
For each s ∈ S:
old-action ← π(s)
π(s) ← argmax a s ,r p(s , r |s, a) r + γV (s )
If old-action = π(s), then policy-stable ← f alse
If policy-stable, then stop and return V ≈ v ∗ and π ≈ π ∗ ; else go to 2`
We should have a separate policy evaluation succeeded by one policy improvement,
but it seems that what I did on my code was value iteration, this one
`Repeat
∆ ← 0
For each s ∈ S:
v ← V (s)
V (s) ← max a s ,r p(s , r |s, a) r + γV (s )
∆ ← max(∆, |v − V (s)|)
until ∆ < θ (a small positive number)
Output a deterministic policy, π ≈ π ∗ , such that`

**Comment by cbrom** [comment]
I am starting to think that the policy evaluation in CarRental being done once does not follow a policy iteration. Because the algorithm for a policy iteration repeats the evaluation process.
