### ISSUE TITLE
question about implementation of dealer's part in blackjack.py

### ISSUE THREAD

**Issue by shining-spring** [ShangtongZhang/reinforcement-learning-an-introduction#69]
The implementation between line 154 and 170 in blackjack.py seems to treat all Aces the dealer might get after the first two cards as one. What if the dealer gets an Ace afterwards which can be used as 11? For example the dealer gets cards (2, 3, A).

Even with 500,000 episodes of running monteCarloES, I sometimes get different results, which suggests that the convergence is not really reached. Do you have any idea which is the best way to check the convergence? 

Thanks a lot.

**Comment by ShangtongZhang** [comment]
Thanks for pointing this out, it's indeed a bug. I just pushed a fix. And I don't have better approach to check the convergence other than more episodes.
