### ISSUE TITLE
Release date - 2nd Edition

### ISSUE THREAD

**Issue by andrewcz** [ShangtongZhang/reinforcement-learning-an-introduction#7]
Any update on when the 2nd edition would be released into print?
Best,
Andrew

**Comment by ShangtongZhang** [comment]
I'm not sure about that. From the project description of CMPUT609, it seems the draft will be finalized in Jan 2017. However I don't know when it will be released into print.
Cheers

**Comment by DiscoverSeanTang** [comment]
it seems that your code for chapter 1 is not so strong. It can't beat anyone when i play with AI. Just curios  why this happens.

**Comment by Thebaide** [comment]
Hi all,

I am a newcomer, and I am wondering if I should start reading the draft of the second edition or if I should wait for the official release ?

regards,
Bastien.

**Comment by ShangtongZhang** [comment]
I would suggest you read it. It's almost complete.

**Comment by Thebaide** [comment]
Thank you very much for your very quick reply.
And do you have any information about when the book will be available ?

**Comment by ShangtongZhang** [comment]
No :<

**Comment by Thebaide** [comment]
Okay,
Thank you anyway.

**Comment by BotYue** [comment]
Hi Shangtong, is there any news this month? Will it be available by the end of this year? Thanks

**Comment by ShangtongZhang** [comment]
Online draft now is complete
http://incompleteideas.net/sutton/book/the-book-2nd.html

**Comment by Shujian2015** [comment]
October 2018 According to https://mitpress.mit.edu/books/reinforcement-learning-second-edition

**Comment by mimoralea** [comment]
October 23rd, 2018 according to https://www.barnesandnoble.com/w/reinforcement-learning-richard-s-sutton/1128512616?ean=9780262039246

**Comment by joelberkeley** [comment]
11 Dec '18 at https://blackwells.co.uk/bookshop/product/Reinforcement-Learning-by-Richard-S-Sutton-Andrew-G-Barto-Francis-Bach-series-editor/9780262039246 and https://www.hive.co.uk/Product/Richard-S-University-of-Alberta-Sutton/Reinforcement-Learning--An-Introduction/22319053
