### ISSUE TITLE
chapter5

### ISSUE THREAD

**Issue by tinglo** [ShangtongZhang/reinforcement-learning-an-introduction#70]
Hi, may I ask about the Blackjack.py file in chapter5?
Why does line 195 add the initial state in trajectory again?
Won't this lead to calculate the initial state repeatedly?
Since at line 137 already append all states in trajectory.
Or do I misunderstand something?
Thanks.

**Comment by tinglo** [comment]
Thank you for your reply.
But the Line 137 appends the state before it changes.
I output every states in an episode:
(the first element is action, the second element is state)
<img width="194" alt="2018-04-29 4 26 41" src="https://user-images.githubusercontent.com/15313125/39404695-002b347c-4bcb-11e8-970b-162aa8d9ae00.png">
And I output the value of the state (False, 14, 4), it shows 0.66666667,
since the count of every states initialize 1, and  state (False, 14, 4) is counted twice-> (1+1)/(1+1+1) = 0.66666667
But the state(False, 14, 4) shouldn't be counted twice.

I'm sorry for asking too much. 
I will introduce this chapter in a class, so I want to understand the deatails.
Thank you very much.

**Comment by ShangtongZhang** [comment]
Oh it's indeed a bug, thanks for pointing this out! I will fix it soon.

**Comment by ShangtongZhang** [comment]
I just pushed the fix, thanks again! It will be much appreciated if you let me know once you find new bugs.

**Comment by tinglo** [comment]
Sure! 
My friends and I are studying RL recently, and your code really helps us understand more clearly!
We're really grateful for these implementations!
