### ISSUE TITLE
One bug on the MountainCar.py in the folder Chapter12

### ISSUE THREAD

**Issue by MathematicalModels** [ShangtongZhang/reinforcement-learning-an-introduction#71]
Dear Shangtong, 

        Code Line No.157 should change from "argmax(values)" to "np.argmax(values)"
since the original code will cause compile error : "global name 'argmax' is not defined" 

Best Regards,
yuqing

**Comment by ShangtongZhang** [comment]
No. https://github.com/ShangtongZhang/reinforcement-learning-an-introduction/issues/51
