### ISSUE TITLE
Chapter 5: Monte Carlo ES initial policy

### ISSUE THREAD

**Issue by jerome-white** [ShangtongZhang/reinforcement-learning-an-introduction#77]
In the example (5.3) the book states

> As the initial policy we use the policy evaluated in the previous blackjack example, that which sticks only on 20 or 21.

However, the implementation in this repository seems to [use random selection](https://github.com/ShangtongZhang/reinforcement-learning-an-introduction/blob/master/chapter05/Blackjack.py#L230) as the initial policy. In fact, I'm unable to reproduce the results in the book if the initial policy is the previous (`targetPolicyPlayer` in this repositories implementation).

Using random selection makes sense if the Monte Carlo ES algorithm is strictly followed (initial policies are "arbitrary"). How did the authors of this implementation know to use random selection instead of the previous policy? If I missed something, knowing what I missed may help in how I continue to read the book.

**Comment by ShangtongZhang** [comment]
It seems I did't notice this sentence when I implemented this so I just used a random one.
> As the initial policy we use the policy evaluated in the previous blackjack example, that which sticks only on 20 or 21.

I have no idea how exactly you use `targetPolicyPlayer` as the initial policy so I can't give further advise. But I will also try it myself in the future.

**Comment by jerome-white** [comment]
```
230c230
<         initialAction = np.random.choice(actions)
---
>         initialAction = int(targetPolicyPlayer(*initialState))
```

**Comment by ShangtongZhang** [comment]
This won't work. By `initial policy` it means the initial policy for the whole training process, not the initial policy for each episode.

**Comment by jerome-white** [comment]
Another interpretation would be to use `targetPolicyPlayer` once for each state, the first time that state has been explored. In this case, the policy array could be viewed as a set: if the state is not in the set, use `targetPolicyPlayer` to decide the action; use `behaviorPolicy` otherwise.

However, in my personal implementation I wasn't able to get this logic to work either. I have the feeling that random is the correct thing to do; I just wish I knew what the authors had in mind when they wrote what they did in the exercise.

**Comment by ShangtongZhang** [comment]
https://github.com/ShangtongZhang/reinforcement-learning-an-introduction/blob/latest/chapter05/blackjack.py#L230

This line may explain how it works
