### ISSUE TITLE
CHAPTER1 ,TicTacToe.py: Purpose of reshape function?

### ISSUE THREAD

**Issue by pk97** [ShangtongZhang/reinforcement-learning-an-introduction#79]
`for i in self.data.reshape(BOARD_ROWS * BOARD_COLS):`

What is the purpose of using reshape staement, line no.34? It works even without it.

**Comment by ShangtongZhang** [comment]
`data` is 2D, `reshape` makes it 1D. The `for` loop should behave differently.
