### ISSUE TITLE
Chapter 8: Backup updates for Prioritized Sweeping vs Dyna-Q

### ISSUE THREAD

**Issue by xenomeno** [ShangtongZhang/reinforcement-learning-an-introduction#80]
Hi,

When comparing the backup updates between the 2 methods for the extended mazes you multiply the actual steps taken by n(planning_steps). Shouldn't be this multiplied by n+1 since it uses n updates in the simulated experience and +1 more update in the real experience?

**Comment by ShangtongZhang** [comment]
I think you are right. I looks like a bug. Would you like to open a PR to fix it? I can do it as well in case you won't.

**Comment by xenomeno** [comment]
I am not sure what PR is as I am new to this github thing?

Danko Jordanov
---------
https://vimeo.com/xenomeno/StuntDemo
http://www.imdb.com/name/nm1242406/
http://www.youtube.com/user/xenomeno79

**Comment by ShangtongZhang** [comment]
Never mind. I will fix it then.

**Comment by ShangtongZhang** [comment]
Fixed in `branch:latest`
