### ISSUE TITLE
Question about gradient in differential semi-gradient Sarsa 

### ISSUE THREAD

**Issue by hukh** [ShangtongZhang/reinforcement-learning-an-introduction#82]
Hello,

How did you calculate and implement the gradient descent in differential semi gradient sarsa algorithm?
I am trying to understand the implementation and for some reason, I can't see how the gradient descent implemented.

Thanks

**Comment by ShangtongZhang** [comment]
Could you be more specific, e.g., specifying the line of a file?

**Comment by hukh** [comment]
Chapter 10 code access_control.py, function "learn" line 157 and 158.
In the book, there is a gradient descent in the algorithm as I understood 
w=w+alpha*delta*gradient descent q(S,A,w)    ,   something like that.

**Comment by ShangtongZhang** [comment]
You can compute \nabla_w q(S, A, w) manually with linear function approximation and binary features. The expansion will end up with the update I did in the two lines.

**Comment by hukh** [comment]
Would you please give more explanation?

**Comment by ShangtongZhang** [comment]
No. In general I only address bugs in the code. It is impossible for me to reply to everyone about all the questions.
