### ISSUE TITLE
Some revision suggestions in Maximization_bias's Problem

### ISSUE THREAD

**Issue by LBAWMY** [ShangtongZhang/reinforcement-learning-an-introduction#86]
I just find that the picture generated by origin codes doesn't match the Figure 6.7 in the Sutton's book.
This is the Figure 6.7 in Sutton's book:
![image](https://user-images.githubusercontent.com/23582671/45481534-613dc300-b77e-11e8-88a4-8a06ef74f3f2.png)
However, the picture generate by origin codes:
![image](https://user-images.githubusercontent.com/23582671/45481584-816d8200-b77e-11e8-83d5-35ee41c773db.png)
I think the problem should be in the line 116,117, I am modifying it to the following code:
`left_counts_q = left_counts_q.mean(axis=0)`
`left_counts_double_q = left_counts_double_q.mean(axis=0)`
This is the new picture generated by the revised code:
![image](https://user-images.githubusercontent.com/23582671/45482032-91d22c80-b77f-11e8-8d9d-0c86341eda0d.png)
This output resembles the Figure 6.7 in Sutton's book.

Another suggestion (Following code used to replace the origin code in line 93): 
`best_action = np.random.choice([action_ for action_, value_ in enumerate(active_q[next_state]) if value_ == np.max(active_q[next_state])])`

**Comment by ShangtongZhang** [comment]
Would like to make a PR?
