### ISSUE TITLE
chap1 tic-tac-toe, get_all_states_impl function, need some explaination

### ISSUE THREAD

**Issue by hitblackjack** [ShangtongZhang/reinforcement-learning-an-introduction#92]
this function is very compact, how do you devicse such a recursive method?  any hint or reference?  thank you.

**Comment by PeterHuang2015** [comment]
devicse？

获取 Outlook for iOS<https://aka.ms/o0ukef>

________________________________
收件人: hitblackjack <notifications@github.com>
发送时间: 星期五, 十二月 7, 2018 3:24 下午
收件人: ShangtongZhang/reinforcement-learning-an-introduction
抄送: Subscribed
主题: [ShangtongZhang/reinforcement-learning-an-introduction] chap1 tic-tac-toe, get_all_states_impl function, need some explaination (#92)


this function is very compact, how do you devicse such a recursive method? any hint or reference? thank you.

―
