### ISSUE TITLE
Chapter 4 jacks car rental

### ISSUE THREAD

**Issue by HareshMiriyala** [ShangtongZhang/reinforcement-learning-an-introduction#93]
I wonder why the key is 10*x+lambda ? shouldnt it be just x ?

**Comment by ShangtongZhang** [comment]
Now I think it is better to use the tuple ```(n, lambda)``` as key directly, which are the parameters of the function. It is unnecessary to encode this tuple myself.

**Comment by HareshMiriyala** [comment]
Thanks. As a beginner, that was confusing to me. Now i understand.
