### ISSUE TITLE
Why do not use true online Sarsa(λ) in figure 12.11

### ISSUE THREAD

**Issue by xingE650** [ShangtongZhang/reinforcement-learning-an-introduction#94]
figure 12.11 in Chapter12 ELIGIBILITY TRACES, shows a curve using true online Sarsa(λ) algorithm, but in code chapter12/mountain_car.py, you use Sarsa(λ) with dutch eligibility trace instead of true online Sarsa(λ). Thank you very much if you answer my naive question.

**Comment by ShangtongZhang** [comment]
Isn't true online Sarsa same as dutch trace?
