### ISSUE TITLE
Missing parameter description for true_reward

### ISSUE THREAD

**Issue by michaelshiyu** [ShangtongZhang/reinforcement-learning-an-introduction#98]
In Chapter 2's ten_armed_testbed.py, the true_reward parameter to the function Bandit.\_\_init\_\_() does not have a parameter description. Here's my suggestion: 

@true_reward: shift the mean of the standard normal distribution from which the action values are sampled to true_reward

Thanks.

**Comment by ShangtongZhang** [comment]
Yeah. The documentation is far from complete. I will fix them when I'm free.

**Comment by michaelshiyu** [comment]
I see. Thanks for replying!
